ProyectoABD/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from superware import views, serilizer

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index, name="index"),
    url(r'^application/', include('superware.urls')),

    url(r'^articulos/$', serilizer.listaArticulos, name="listaArticulos"),
    url(r'^obtenerArticulo/$', serilizer.getArticulo, name="getArticulo"),

]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

superware/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url

from superware import views

app_name = 'superware'

urlpatterns = [
    #url(r'^registrarse/$', views.registrarse, name='registrarse'), #nombre para identificar en html
    #url(r'^usuario_login/$', views.usuario_login, name="usuario_login"),
    url(r'^login/$', views.usuario_login, name="login"),
    url(r'^logout/$', views.usuario_logout, name="logout"),
    url(r'^consultas/$', views.consultas, name="consultas"),
    url(r'^ventas/$', views.index, name="ventas"),
    url(r'^inventario/$', views.listarInventario, name="listarInventario"),
    url(r'^estadisticas/$', views.estadisticas, name="estadisticas"),
    url(r'^agregarArticulo/$', views.agregarArticulo, name="agregarArticulo"),
    url(r'^respaldos/$', views.menuRespaldos, name="menuRespaldos"),
    url(r'^nuevoRespaldo/$', views.crearRespaldo, name="crearRespaldo"),
    url(r'^restaurarUltimo/$', views.restaurarUltimo, name="restaurarUltimo"),
    url(r'^editarArticulo/(?P<idarticulo>\w+)/$', views.editarArticulo, name="editarArticulo"),
    url(r'^eliminarArticulo/(?P<idarticulo>\w+)/$', views.eliminarArticulo, name="eliminarArticulo"),
    url(r'^agregarAlCarrito$', views.agregarArticuloCarrito, name="agregarArticuloCarrito"),
    url(r'^addToCart', views.addToCart, name="addToCart"),
    url(r'^finalizarCobro', views.finalizarCobro, name="finalizarCobro"),
    url(r'^ticket/(?P<folio>\w+)/', views.ticket, name="ticket"),

]

templates/agregarArticulo.html
{% extends 'index.html' %}
{% load staticfiles %}

{% block contenido %}
    <div class="col-md-12">
        <div class="card card-plain">
            <div class="header">
                <h4 class="title">Agrega un articulo al inventario</h4>
                <p class="category">Datos de articulo:</p>
            </div>

            <form method="post" enctype="multipart/form-data" action="{% url 'superware:agregarArticulo' %}">
                {% csrf_token %}
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="col-xs-4 col-sm-5 col-md-6 col-lg-6">
                    {{ form }}
                    <br>
                    <button type="submit" class="btn btn-primary btn-fill">
                        <i class="ti-save"></i> AGREGAR ARTICULO
                    </button>
                </div>

            </form>


        </div>
    </div>
{% endblock %}

templates/editarArticulo.html
{% extends 'index.html' %}
{% load staticfiles %}

{% block contenido %}
    <div class="col-md-12">
        <div class="card card-plain">
            <div class="header">
                <h4 class="title">Agrega un articulo al inventario</h4>
                <p class="category">Datos de articulo:</p>
            </div>

            <form method="post" enctype="multipart/form-data" action="{% url 'superware:editarArticulo' id %}">
                {% csrf_token %}
                {% if form.errors %}
                    {% for field in form %}
                        {% for error in field.errors %}
                            <div class="alert alert-danger">
                                <strong>{{ error|escape }}</strong>
                            </div>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <div class="alert alert-danger">
                            <strong>{{ error|escape }}</strong>
                        </div>
                    {% endfor %}
                {% endif %}
                <div class="col-xs-4 col-sm-5 col-md-6 col-lg-6">
                    {{ form }}
                    <br>
                    <button type="submit" class="btn btn-primary btn-fill">
                        <i class="ti-save"></i> AGREGAR ARTICULO
                    </button>
                </div>

            </form>


        </div>
    </div>
{% endblock %}

templates/estadisticas.html
{% extends 'index.html' %}
{% load staticfiles %}

{% block modulo %}
    <ul class="nav">
        <li>
            <a href="{% url 'superware:ventas' %}">
                <i class="ti-shopping-cart-full"></i>
                <p>Ventas</p>
            </a>
        </li>
        <li>
            <a href="{% url 'superware:listarInventario' %}">
                <i class="ti-server"></i>
                <p>Inventario</p>
            </a>
        </li>
        <li>
            <a href="{% url 'superware:consultas' %}">
                <i class="ti-view-list-alt"></i>
                <p>Consultas</p>
            </a>
        </li>
        <li class="active">
            <a href="{% url 'superware:estadisticas' %}">
                <i class="ti-stats-up"></i>
                <p>Estadisticas</p>
            </a>
        </li>
        <li class="active-pro">
            <a href="{% url 'superware:logout' %}">
                <i class="ti-shift-left"></i>
                <p>Salir</p>
            </a>
        </li>
    </ul>
{% endblock %}

{% block contenido %}
    <div class="content">
    <div class="row">

        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <h4 class="title">Ventas</h4>
                    <p class="category">Ultimas ventas</p>
                </div>
                <div class="content">
                    <div id="chartHours" class="ct-chart"></div>
                    <div class="footer">
                        <div class="chart-legend">
                            <i class="fa fa-circle text-info"></i> Ropa
                            <i class="fa fa-circle text-danger"></i> Limpieza
                            <i class="fa fa-circle text-warning"></i> Otros
                        </div>
                        <hr>
                        <div class="stats">
                            <i class="ti-reload"></i> Actualizado
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block extraCode %}
    <script>
        $(document).ready(function () {
            var dataSales = {
                labels: ['9:00AM', '12:00AM', '3:00PM', '6:00PM', '9:00PM', '12:00PM', '3:00AM', '6:00AM'],
                series: [
                    [287, 385, 490, 562, 594, 626, 698, 895, 952],
                    [67, 152, 193, 240, 387, 435, 535, 642, 744],
                    [123, 1113, 167, 1108, 190, 239, 307, 410, 410]
                ]
            };

            var optionsSales = {
                lineSmooth: false,
                low: 0,
                high: 1000,
                showArea: true,
                height: "245px",
                axisX: {
                    showGrid: false,
                },
                lineSmooth: Chartist.Interpolation.simple({
                    divisor: 3
                }),
                showLine: true,
                showPoint: false,
            };

            var responsiveSales = [
                ['screen and (max-width: 640px)', {
                    axisX: {
                        labelInterpolationFnc: function (value) {
                            return value[0];
                        }
                    }
                }]
            ];

            Chartist.Line('#chartHours', dataSales, optionsSales, responsiveSales);


            var data = {
                labels: ['Jan', 'Feb', 'Mar', 'Apr', 'Mai', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                series: [
                    [542, 543, 520, 680, 653, 753, 326, 434, 1568, 1610, 1756, 1000],
                    [230, 293, 380, 480, 503, 553, 600, 664, 698, 710, 736, 795]
                ]
            };

            var options = {
                seriesBarDistance: 10,
                axisX: {
                    showGrid: false
                },
                height: "245px"
            };

            var responsiveOptions = [
                ['screen and (max-width: 640px)', {
                    seriesBarDistance: 5,
                    axisX: {
                        labelInterpolationFnc: function (value) {
                            return value[0];
                        }
                    }
                }]
            ];

            Chartist.Line('#chartActivity', data, options, responsiveOptions);

            var dataPreferences = {
                series: [
                    [25, 30, 20, 25]
                ]
            };

            var optionsPreferences = {
                donut: true,
                donutWidth: 40,
                startAngle: 0,
                total: 100,
                showLabel: false,
                axisX: {
                    showGrid: false
                }
            };

            Chartist.Pie('#chartPreferences', dataPreferences, optionsPreferences);

            Chartist.Pie('#chartPreferences', {
                labels: ['62%','32%','6%'],
                series: [62, 32, 6]
            });
        });
    </script>
{% endblock %}

templates/index.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/shop.png' %}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <title>SuperWare punto de venta</title>

    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />


    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" />

    <link href="{% static 'css/animate.min.css'%}" rel="stylesheet"/>

    <link href="{% static 'css/paper-dashboard.css'%}" rel="stylesheet"/>

    <link href="{% static 'css/demo.css'%}" rel="stylesheet" />


    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-notify/0.2.0/css/bootstrap-notify.css" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
    <link href="{% static 'css/themify-icons.css' %}" rel="stylesheet">

</head>
<body>

<div class="wrapper">
    <div class="sidebar" data-background-color="black" data-active-color="danger">

        <div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    SUPERWARE <br>
                </a>
            </div>
            {% block modulo %}
                <ul class="nav">
                    <li class="active">
                        <a href="{% url 'superware:ventas' %}">
                            <i class="ti-shopping-cart-full"></i>
                            <p>Ventas</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'superware:listarInventario' %}">
                            <i class="ti-server"></i>
                            <p>Inventario</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'superware:consultas' %}">
                            <i class="ti-view-list-alt"></i>
                            <p>Consultas</p>
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'superware:estadisticas' %}">
                            <i class="ti-stats-up"></i>
                            <p>Estadisticas</p>
                        </a>
                    </li>
                    <li class="active-pro">
                        <a href="{% url 'superware:logout' %}">
                            <i class="ti-shift-left"></i>
                            <p>Salir</p>
                        </a>
                    </li>
                </ul>
            {% endblock %}
        </div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="#"> Usuario: {{ usuario.nombre }} {{ usuario.apellidoP }} {{ usuario.apellidoM }}<br>
                        Puesto: <i>{{ usuario.puesto }}</i></a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        {% comment %}<li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="ti-bell"></i>
                                <p class="notification">5</p>
                                <p>Notificaciones</p>
                                <b class="caret"></b>
                            </a>
                            <ul class="dropdown-menu">
                                <li><a href="#">Notificación</a></li>
                                <li><a href="#">Notificación 2</a></li>
                                <li><a href="#">Notificación 3</a></li>
                                <li><a href="#">Notificación 4</a></li>
                                <li><a href="#">Ver más...</a></li>
                            </ul>
                        </li>{% endcomment %}
                        <li>
                            <a href="{% url 'superware:menuRespaldos' %}">
                                <i class="ti-settings"></i>
                                <p>Administración BD</p>
                            </a>
                        </li>
                    </ul>

                </div>
            </div>
        </nav>

        {% block contenido %}


        {% endblock %}
    </div>
</div>

{% block modal %}

{% endblock %}

</body>

<script src="{% static 'js/jquery-1.10.2.js'%}" type="text/javascript"></script>
<script src="{% static 'js/bootstrap.min.js'%}" type="text/javascript"></script>

<script src="{% static 'js/bootstrap-checkbox-radio.js'%}"></script>

<script src="{% static 'js/chartist.min.js'%}"></script>

<script src="{% static 'js/bootstrap-notify.js'%}"></script>

<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>

<script src="{% static 'js/paper-dashboard.js'%}"></script>

<script src="{% static 'js/demo.js'%}"></script>

{% block extraCode %}

{% endblock %}

</html>

templates/inventario.html
{% extends 'index.html' %}
{% load staticfiles %}
{% load permission_tags %}

{% block modulo %}
    <ul class="nav">
        <li>
            <a href="{% url 'superware:ventas' %}">
                <i class="ti-shopping-cart-full"></i>
                <p>Ventas</p>
            </a>
        </li>
        <li class="active">
            <a href="{% url 'superware:listarInventario' %}">
                <i class="ti-server"></i>
                <p>Inventario</p>
            </a>
        </li>
        <li>
            <a href="{% url 'superware:consultas' %}">
                <i class="ti-view-list-alt"></i>
                <p>Consultas</p>
            </a>
        </li>
        <li>
            <a href="estadisticas.html">
                <i class="ti-stats-up"></i>
                <p>Estadisticas</p>
            </a>
        </li>
        <li class="active-pro">
            <a href="{% url 'superware:logout' %}">
                <i class="ti-shift-left"></i>
                <p>Salir</p>
            </a>
        </li>
    </ul>
{% endblock %}

{% block contenido %}
    {% if mensaje %}
        <script>
            alert("Transacción hecha correctamente");
        </script>
    {% endif %}
    <div class="content">
        <div class="col-lg-3 col-sm-4">
            <div class="card">
                <div class="content">
                    <div class="row">
                        <div class="col-xs-3">
                            <div class="icon-big icon-info text-center">
                                <i class="ti-reload"></i>
                            </div>
                        </div>
                        <div class="col-xs-3">
                            <div class="numbers">
                                <p><a class="btn btn-success btn-fill" href="{% url 'superware:agregarArticulo' %}">Agregar articulo</a></p>
                                <p>&ensp;</p>
                                <p><button class="btn btn-info btn-fill" onclick="displayBuscar()">Buscar articulo(s)</button></p>
                            </div>
                            <div class="buscarDiv form-group">
                                <br>
                                <label for="search">Busqueda:</label>
                                <input type="text" id="search">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="card card-plain">
                <div class="header">
                    <h4 class="title">Articulos de bodega</h4>
                    <p class="category">lista de articulos y sus cantidades</p>
                </div>
                <div class="content table-responsive table-full-width">
                    <table class="table table-hover">
                        <thead>
                        {#                        <th>ID</th>#}
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Stock</th>
                        <th>Stock minimo</th>
                        <th>Acciones</th>
                        </thead>
                        <tbody>
                        {% for articulo in articulos %}
                            <tr>
                                {#                                <td>{{ forloop.counter }}</td>#}
                                <td>{{ articulo.nombre }}</td>
                                <td><b><font color="green">${{ articulo.precio }}</font></b></td>
                                <td>{{ articulo.stock }}</td>
                                <td>10</td>
                                <td>
                                    {% if user|can:'inventarioEditarEliminar' %}
                                        <a class="btn btn-sm btn-info btn-icon" href="{% url 'superware:editarArticulo' articulo.pk %}"><i class="fa ti-pencil"></i></a>
                                        <a class="btn btn-sm btn-danger btn-icon" href="{% url 'superware:eliminarArticulo' articulo.pk %}"><i class="fa ti-close"></i></a>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>
        </div>

    </div>
{% endblock %}

{% block extraCode %}
    <script>
        $("#search").on("keyup", function() {
            var value = $(this).val();

            $("table tr").each(function(index) {
                if (index !== 0) {

                    $row = $(this);

                    var id = $row.find("td:first").text();

                    if (id.indexOf(value) !== 0) {
                        $row.hide();
                    }
                    else {
                        $row.show();
                    }
                }
            });
        });
    </script>
{% endblock %}

templates/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" >

<head>
    <meta charset="UTF-8">
    <title>Login SuperWare</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css">
    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css'>
    <link rel="stylesheet" href="{% static 'login/css/style.css' %}">
</head>

<body>

<form class="login" action="{% url 'superware:login' %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend class="legend">Login SuperWare</legend>
        <div class="input">
            <input type="text" placeholder="Usuario" required name="usuario"/>
        </div>

        <div class="input">
            <input type="password" placeholder="Contraseña" required name="pass"/>
        </div>
        <button type="submit" class="submit"><i class="fa fa-long-arrow-right"></i></button>
    </fieldset>

    {% comment %}<div class="feedback">
        Credenciales correctas! <br />
        Entrando...
    </div>{% endcomment %}

</form>
<script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
{#<script  src="{% static 'login/js/index.js' %}"></script>#}
</body>

</html>

templates/respaldos.html
{% extends 'index.html' %}
{% load staticfiles %}

{% block contenido %}
    {% if mensaje %}
        <script>
            alert("Operación realizada exitosamente");
            window.history.back();
        </script>
    {% endif %}
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-4 col-md-5">
                    <div class="card card-user">
                        <div class="image">
                            <img src="{% static 'img/backup.png' %}" alt="..."/>
                        </div>
                        <div class="content">
                            <p class="description text-center">
                                Aquí restaura a la ultima versión de respaldo que se tenga <br>
                                en la base de datos.
                            </p>
                        </div>
                        <hr>
                        <div class="text-center">
                            <div class="row">
                                <div class="col-md-3 col-md-offset-1">
                                    <a href="{% url 'superware:restaurarUltimo' %}" class="btn btn-primary btn-fill">Restaurar a ultimo respaldo</a>
                                </div>
                                <div class="col-md-2">
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <div class="col-lg-8 col-md-7">
                    <div class="card card-user">
                        <div class="image">
                            <img src="{% static 'img/backup2.jpeg' %}" alt="..."/>
                        </div>
                        <div class="content">
                            <p class="description text-center">
                               Ejecutar un nuevo respaldo de la base de datos. <br>
                                Esta opción permite crear un respaldo de la base de datos automaticamente
                            </p>
                        </div>
                        <hr>
                        <div class="text-center">
                            <div class="row">
                                <div class="col-md-3 col-md-offset-1">
                                    <a href="{% url 'superware:crearRespaldo' %}" class="btn btn-primary btn-fill">Nuevo Respaldo</a>
                                </div>
                                <div class="col-md-2">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/ticket.html
{% extends 'index.html' %}
{% load staticfiles %}
{% load permission_tags %}

{% block contenido %}
    <style>
        .cardWrap {
            width: 27em;
            margin: 3em auto;
            color: #fff;
            font-family: sans-serif;
        }

        .card {
            background: linear-gradient(to bottom, #343434 0%, #e84c3d 26%, #ecedef 26%, #ecedef 100%);
            height: 11em;
            float: left;
            position: relative;
            padding: 1em;
        }

        .cardLeft {
            border-top-left-radius: 8px;
            border-bottom-left-radius: 8px;
            width: 16em;
        }

        .cardRight {
            width: 6.5em;
            border-left: .18em dashed #fff;
            border-top-right-radius: 8px;
            border-bottom-right-radius: 8px;
        }
        .cardRight:before, .cardRight:after {
            content: "";
            position: absolute;
            display: block;
            width: .9em;
            height: .9em;
            background: #fff;
            border-radius: 50%;
            left: -.5em;
        }
        .cardRight:before {
            top: -.4em;
        }
        .cardRight:after {
            bottom: -.4em;
        }

        h1 {
            font-size: 1.1em;
            margin-top: 0;
        }
        h1 span {
            font-weight: normal;
        }

        .title, .name, .seat, .time {
            text-transform: uppercase;
            font-weight: normal;
        }
        .title h2, .name h2, .seat h2, .time h2 {
            font-size: .9em;
            color: #525252;
            margin: 0;
        }
        .title span, .name span, .seat span, .time span {
            font-size: .7em;
            color: #a2aeae;
        }

        .title {
            margin: 2em 0 0 0;
        }

        .name, .seat {
            margin: .7em 0 0 0;
        }

        .time {
            margin: .7em 0 0 1em;
        }

        .seat, .time {
            float: left;
        }

        .number {
            text-align: center;
            text-transform: uppercase;
        }
        .number h3 {
            color: midnightblue;
            margin: .9em 0 0 0;
            font-size: 1em;
        }
        .number span {
            display: block;
            color: #a2aeae;
        }

    </style>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/prefixfree/1.0.7/prefixfree.min.js"></script>

    <h2>Cobro realizado exitosamente</h2>
    <div class="cardWrap">
        <div class="card cardLeft">
            <h1>Super <span>Ware</span></h1>
            <div class="title">
                {% for articulo in articulos %}
                    <h2>{{ articulo.nombre }}</h2>
                    <span>$ {{ articulo.precio }}</span>
                {% endfor %}
            </div>
            <div class="seat">
                <h2>Total: </h2>
            </div>
            <div class="time">
                <h2>${{ total }}</h2>
            </div>

        </div>
        <div class="card cardRight">
            <div><i class="ti-shopping-cart"></i></div>
            <div class="number">
                <h3>{{ fecha }}</h3>
            </div>
        </div>
        <a href="{% url 'superware:ventas' %}" class="btn btn-info btn-fill">Regresar a ventas</a>
    </div>

{% endblock %}